version: '3.8'

services:
  weather-app-1:
    build: .
    ports:
      - "8081:8080"
    environment:
      - INSTANCE_NAME=weather-app-1
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  weather-app-2:
    build: .
    ports:
      - "8082:8080"
    environment:
      - INSTANCE_NAME=weather-app-2
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  haproxy:
    image: haproxy:2.8-alpine
    ports:
      - "80:80"
      - "8404:8404"  # HAProxy stats page
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - weather-app-1
      - weather-app-2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8404/stats"]
      interval: 30s
      timeout: 10s
      retries: 3